version: '3'
services:
  rpi:
    build:
      context: ./fake_rpi
      dockerfile: Dockerfile
    command: /bin/bash -c "cd catkin_ws && rm -rf build devel && catkin build -DCMAKE_BUILD_TYPE=Release && source devel/setup.bash && tail -f /dev/null"
    
    volumes:
            - "${SRC}/mantaray_rpi:/home/mantaray/catkin_ws/src/mantaray_rpi"
            - "${SRC}/control-toolbox:/home/mantaray/catkin_ws/src/control-toolbox"
            - "${SRC}/kindr:/home/mantaray/catkin_ws/src/kindr"
    network_mode: host
  sim:
    build:
      context: ./sim
      dockerfile: Dockerfile
    command: /bin/bash -c "cd scripts && ./init.sh && ./run_sim.sh; tail -f /dev/null"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${XAUTH:-/tmp/.docker.xauth}:${XAUTH:-/tmp/.docker.xauth}"
      - "${SRC}/mantaray_xavier:${CATKIN_WS}/src/mantaray_xavier"
      - "${SRC}/USCAUVSim:${CATKIN_WS}/src/USCAUVSim"
      - "${SRC}/USCAUVSim/scripts:/home/mantaray/scripts"
      - ""
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    runtime: nvidia

